name: productive
description: A Flutter app for productivity tracking
version: 1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3

flutter:
  uses-material-design: true