// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVCEhzyuQHfx9MIrGtsijUi1a12olfMkE',
    appId: '1:237273249063:web:5245dfa86b2d9ff9722502',
    messagingSenderId: '237273249063',
    projectId: 'productive-5d855',
    authDomain: 'productive-5d855.firebaseapp.com',
    databaseURL: 'https://productive-5d855-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'productive-5d855.appspot.com',
    measurementId: 'G-VFMD90NVDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsSiEBZO3wPHwRY7UXw7FoO-NGv_h4nFA',
    appId: '1:237273249063:android:35e131af396dd8f9722502',
    messagingSenderId: '237273249063',
    projectId: 'productive-5d855',
    databaseURL: 'https://productive-5d855-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'productive-5d855.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqkeSIKCiFqH5eS8mOiPBX2ejkCUho20E',
    appId: '1:237273249063:ios:a2ff0ec807c16bcc722502',
    messagingSenderId: '237273249063',
    projectId: 'productive-5d855',
    databaseURL: 'https://productive-5d855-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'productive-5d855.appspot.com',
    iosBundleId: 'com.example.productive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqkeSIKCiFqH5eS8mOiPBX2ejkCUho20E',
    appId: '1:237273249063:ios:365e56d21ccafee1722502',
    messagingSenderId: '237273249063',
    projectId: 'productive-5d855',
    databaseURL: 'https://productive-5d855-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'productive-5d855.appspot.com',
    iosBundleId: 'com.example.productive.RunnerTests',
  );
}
